### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Darth-Mera** [engelmi/hirte#31]
I'm opening this issue as a place to discuss developing a plan on how to test this project, as per our agreement in the chat.

**Comment by engelmi** [comment]
Adding a first proposal here :)

I'd define two different scopes for tests: 

### Unit Testing

These are developer focused and test only one function or a small set of functions. Therefore, they (should) have no external dependencies and are executed fast. Perfect for CI for basic functionality verification. 

How this can be done without any library you can see [here](https://github.com/engelmi/orch/blob/main/test/common/parse-util_test.c). One pain point is to define the compile command (used `.c` files etc.) for each individually. But using a build system like `meson` helps. Testing libraries might not really help here. However, those libs might be useful for other concepts like mocking, etc.. But for now, I think this is a basic, yet efficient first approach for unit testing this project. 


### End-to-End Testing

These are feature focused and test the whole system. In our case it comprises of the `node`, `orchestrator` and sytemd unit files - and a `client` to trigger everything  (and/or a monitoring tool, etc.). 

Since e2e tests should be as close to the actual environment as possible, it would be great to have a setup with multiple machines (e.g. via VMs) - one VM runs the orchestrator, the others the node application. We could also think about containerizing the binaries, but that might be not straight-forward and we might run into other issues. 
For testing a feature such as `blue chihuahua can start a unit on all connected remote nodes`, we define specific systemd units to start. Finally, the client can be used to trigger the respective unit.
The verification part would rely on the dbus - waiting for specific signals that are emitted from systemd -> node -> orch -> client (omitting the dbusses involved).  


### Conclusion

We can start with the Unit Testing right now. The e2e testing requires more features to be available, but the setup (e.g. VMs, unit files, etc.) can be prepared already. 


### Side note about Test Coverage

To get a feeling of which parts of our code we tested, we can use 
- [gcov](https://gcc.gnu.org/onlinedocs/gcc/Gcov.html)
- and [gcovr](https://gcovr.com/en/stable/)

These can definitely be used for the unit tests, and maybe also for the e2e tests.

**Comment by sdunnagan** [comment]
Great overview of the options for testing Blue Chihuahua!  This helped me understand the various objectives.  I see now that what I was proposing with testing the original orch with some containers is really an e2e test.  We might should add unit tests alongside features as they are being developed.

**Comment by Yarboa** [comment]
For e2e testing adding issue #118  #119
@sdunnagan can we close this issue? #35

**Comment by sdunnagan** [comment]
@Darth-Mera Can we close this issue?

**Comment by Darth-Mera** [comment]
@sdunnagan Sure!
