### ISSUE TITLE
hirte-agent doesn't respect the -c flag.

### ISSUE THREAD

**Issue by dougsland** [engelmi/hirte#371]
## Describe the bug

`hirte-agent` doesn't respect the `-c flag`.

## To Reproduce

Please provide the steps to reproduce the issue.

1. Edit  /usr/local/share/hirte-agent/config/agent.conf add:
```
ManagerHost=fd00::1:8:7
```

2. Edit /etc/hirte/agent.conf and **comment all ManagerHosts entries**
```
# The IP address that hirte-agent can use to connect to hirte manager. It must be a valid IPv4 or IPv6 address.
# One of the ManagerHost or ManagerAddress options must be set for each hirte-agent.
#ManagerHost=10.90.0.7
#ManagerHost=control.medogz.com
#ManagerHost=fd00::1:8:7
```

3. Start the agent asking to read the config file from **/etc/hirte/agent.conf** ONLY
```
./builddir/src/agent/hirte-agent -c /etc/hirte/agent.conf
```

4. It will read the ManagerHost from `/usr/local/share/hirte-agent/config/agent.conf` and **NOT respect** the `-c`.
```
# ./builddir/src/agent/hirte-agent -c /etc/hirte/agent.conf
2023-06-27 14:13:06,643+0000 INFO	: Connecting to manager on tcp:host=fd00::1:8:7,port=842
2023-06-27 14:13:06,644+0000 INFO	: Connected to manager as 'node1'
```
More info:
```
# ./builddir/src/agent/hirte-agent --help
        <SNIP>
	-c config	 A path to a config file used to bootstrap hirte-agent.
        <SNIP>
```

## Expected behavior
hirte-agent should respect the config specified by user and read only the config provided.

**Comment by dougsland** [comment]
I was investigating some config loading and found this. I will take a look how this part of code  works.

**Comment by engelmi** [comment]
The described behavior is expected (and desired). 
`hirte` and `hirte-agent` always read multiple configuration files (if present) from different locations and the settings from files that are read later override the previously set ones. In the described case above, `hirte-agent` still reads the configuration as ` /usr/local/share/hirte-agent/config/agent.conf`. It also reads the file passed in by the `-c` option - but since all settings are commented out, it basically has no effect. 
How the configuration files work in hirte is also explained [here](https://hirte.readthedocs.io/en/latest/configuration/).

**Comment by engelmi** [comment]
Closing this issue. If you think we should refactor how the configuration works, please reopen this issue @dougsland
