### ISSUE TITLE
Add D-Bus API to get system resources of node

### ISSUE THREAD

**Issue by dofmind** [engelmi/hirte#589]
How about to add D-BUS API to get system resources (like cpu time and memory usage) of node? The API will help know how much the node consumes the system resources, so state manager can choose a proper node to execute unit. For example, kubernetes scheduler selects a fit node to run the pod based on resources of each node.

**Comment by engelmi** [comment]
Hi @dofmind, thank you for the good question!
I agree with the use case you describe - information about the system resources such as cpu time, memory usage, disk usage, etc. is very useful for an "BlueChi-external" state manager to have. However, systemd does not expose anything like that on its DBus interfaces (as far as I know). And since BlueChi is designed to be only a thin extension to systemd, I am afraid this feature does not fit in BlueChi from a design perspective. 
This use case is probably best addressed by employing a dedicated telemetry application to collect such metrics and provide it to the state manager, e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver.
