### ISSUE TITLE
Cannot detect disconnection of node during d-bus operation

### ISSUE THREAD

**Issue by dofmind** [engelmi/hirte#652]
Scenario: 

Two nodes connected in same network. One node runs bluechi-controller and another node runs bluechi-agent. The bluechi-agent connected to bluechi-controller. To detect network disconnection quickly, i set tcp_keepalive_probes to 1 on each nodes like 
`echo 1 > /proc/sys/net/ipv4/tcp_keepalive_probes`

Run follow command repeatably on node running bluechi-controller, and disconnect LAN cable of node running bluechi-agent.
`bluechictl list-units`

I am monitoring node connection via `bluechictl monitor node-connection` on node running bluechi-controller, but cannot detect disconnection of node running bluechi-agent, still STATE is online.

If i am not running `bluechictl list-units` command, can detect disconnection of node running bluechi-agent.

During d-bus operation, disconnection detection by keep-alive of TCP socket is not working?

**Comment by engelmi** [comment]
Thank you for the bug report @dofmind 
I'll try to reproduce this in order to track down the root cause. How frequently are you calling `bluechictl list-units`?

Edit: 
BlueChi uses a systemd internal signal emitted on the peer D-Bus to detect if an agent has lost connection - the keepalive of TCP sockets is not used (as far as I know).

**Comment by dofmind** [comment]
> Thank you for the bug report @dofmind I'll try to reproduce this in order to track down the root cause. How frequently are you calling `bluechictl list-units`?

I used follow script
```
#!/bin/sh

while true; do bluechictl list-units; sleep 1; done
```

> 
> Edit: BlueChi uses a systemd internal signal emitted on the peer D-Bus to detect if an agent has lost connection - the keepalive of TCP sockets is not used (as far as I know).

As you said, BlueChi handles "Disconnected" signal - https://github.com/eclipse-bluechi/bluechi/blob/1d482eeabad67157bdca17ce5008a07841bd5575/src/manager/node.c#L780

"Disconnected" signal is emitted by systemd? How does systemd detect disconnection of TCP  socket?

Current Bluechi sets keepalive options for TCP socket of peer dbus using bus_socket_set_keepalive() function - 
https://github.com/eclipse-bluechi/bluechi/blob/1d482eeabad67157bdca17ce5008a07841bd5575/src/libbluechi/bus/utils.c#L309

**Comment by engelmi** [comment]
Thanks, I'll try to reproduce this behavior. 

> "Disconnected" signal is emitted by systemd? How does systemd detect disconnection of TCP socket?

Yes, "Disconnected" is a systemd internally defined signal. I don't know when it is emitted currently, I'll have to check in systemd itself or ask the developers there. I assume that the signal "Disconnected" is emitted independently of the tcp keepalive, though. 

What does your script output when the cable is removed from node? Is it an error, just an empty reply or does it even hang? Also, is the disconnect detected by the agent?

**Comment by dofmind** [comment]
> What does your script output when the cable is removed from node? Is it an error, just an empty reply or does it even hang?

`Connection timed out` log is printed at intervals of 25 seconds approximately.
```
...
ak7_master_main     |dbus.service                                               |   active|  running
ak7_master_main     |session-c1.scope                                           |   active|  running
Failed to issue method call: Connection timed out
Call to manager failed: Connection timed out
Failed to issue method call: Connection timed out
Call to manager failed: Connection timed out
Failed to issue method call: Connection timed out
Call to manager failed: Connection timed out
...
```
> Also, is the disconnect detected by the agent?

Case by case, sometimes agent detects the disconnection but sometime agent doesn't detect the disconnection.
This is log when agent detects the disconnection.
```
...
Nov 30 10:43:54 42dot-ak7 bluechi-agent[1036]: Failed to emit heartbeat signal: Transport endpoint is not connected
Nov 30 10:43:54 42dot-ak7 bluechi-agent[1036]: Disconnected from manager
Nov 30 10:43:54 42dot-ak7 bluechi-agent[1036]: Connecting to manager on tcp:host=192.168.16.101,port=842
...
```

**Comment by engelmi** [comment]
I was able to reproduce the issue using your described setup @dofmind . Using two machines - one running the controller, the other the agent - in the same network and then removing the agent machine from the network (e.g. via unplugging the eth cable). 

It seems to be independent of the BlueChi method being called, e.g. start, stop, etc. can also cause this problem. I recorded the network traffic and in a "normal" setting we would like to see:

![image](https://github.com/eclipse-bluechi/bluechi/assets/26504678/e276b6c6-b4a5-48bf-98ea-4fa0db3b71c4)

Basically the keep-alive every second as configured. 

---
Now unplugging the eth cable from the agent machine and we get this:

![image](https://github.com/eclipse-bluechi/bluechi/assets/26504678/0ba8e060-3f6e-4ffa-8ff5-074edf25009b)

After the 9th time (net.ipv4.tcp_keepalive_probes = 9 in my case), the connection was reset and `bluechi-controller` detected the disconnect. So in this setting, it took around 9s to detect the disconnected agent. 

---
Now lets unplug the cable and - within those 9s - submit any command that is forwarded to the agent (e.g. `bluechictl start <node> <service>`). Here is the interesting part of the sniffed traffic:

![image](https://github.com/eclipse-bluechi/bluechi/assets/26504678/febc89c7-ad4b-4d58-b552-5499ef00201b)

There is a keep-alive (since the connection hasn't been used then) followed by the packet for the start command to the agent and a few retransmissions. Finally it "gets stuck" sending ICMP packets, which seems to keep the socket alive even though we clearly have no connection.

---
Looking at BlueChi, we receive the timeouts, but don't handle them properly (other than forwarding the error to the caller). Therefore, I think there are two tasks to be done to solve this:
- On a timeout `bluechi-controller` should trigger a node disconnect. This way, the node is removed on the controller side and marked as offline as expected. The agent can re-register itself as soon as its connection is back. I did a small POC and it seems to work fine. 
- In addition, the timeout should be configurable - currently hard-coded at 30s (which seems to be rather long). This timeout also needs to be set via `sd_bus_set_method_call_timeout` since not calling this function implies a 25s timeout... so the `BC_DEFAULT_DBUS_TIMEOUT 30` is actually not working. 

I am wondering if this is in some way related to #648, but I need to dig deeper here. (/cc @dougsland, just FYI)

**Comment by engelmi** [comment]
@alexlarsson What do you think? Is the node disconnect on timeout a viable option?

**Comment by alexlarsson** [comment]
I think we should be very vary about using method timeouts that way. That is a high-level timeout that measures the complete time before a method call gets a reply (including message send/reply time, as well as executing the method itself). You may have many outstanding operations, and one of them might take a bit longer to service in the agent. That doesn't mean the connection is down.

What worries me is that its clearly seeing the host unreachable, yet is not reporting the disconnect. Maybe this is an issue we could fix in systemd-bus, maybe even by tweaking some setting.

In general, the way socket IPC work is that you have the file descriptor in an fd-set in some poll() mainloop.  If at any point there is data available the socket will be marked as readable or with an error condition, and the mainloop wakes up and reads. At this point it may get an error from read() and decide that the peer was disconnected (or it may just look at the error state from poll(), i believe a tcp socket that gets a RST is marked POLLERR, but many mainloops ignore this and still do the read). 

At this point systemd-bus should send the disconnected signal to the app. However, given the research in this issue it seems that if there is an outstanding message waiting for a reply, then this is not emitted. That seems weird, and I wonder if this is expected or if it is a bug. That is worth researching. 

What would be good is getting a strace log from when this happens so we can see how bluechi-controller acts (i.e. what systemd-bus does) on the syscall level.

Here is the disconnect emitted:

https://github.com/systemd/systemd/blob/bf35f9c83541785726dce41e54496a07f4841621/src/libsystemd/sd-bus/sd-bus.c#L3184C9-L3184C9

Might be interesting to see if that is reached in this case.

**Comment by alexlarsson** [comment]
bus_enter_closing() seems to be what triggers this, and is what should happen after the destination unreachable is returned somewhere.

**Comment by alexlarsson** [comment]
As far as I understand it, this is where a read error should trigger a disconnect:

https://github.com/systemd/systemd/blob/bf35f9c83541785726dce41e54496a07f4841621/src/libsystemd/sd-bus/sd-bus.c#L3283

There are other places too, like e.g when send() returns a failure, but in our case of "otherwise idle" this is where it would hit.

**Comment by engelmi** [comment]
Thank you for your feedback! @alexlarsson 

I think I found a suitable fix for this issue: setting the `IP_RECVERR` socket option

As you suggested, I created straces from the different cases:
- [trace-disconnect-without-cmd.txt](https://github.com/eclipse-bluechi/bluechi/files/13701038/trace-disconnect-without-cmd.txt)
- [trace-disconnect-with-cmd.txt](https://github.com/eclipse-bluechi/bluechi/files/13701032/trace-disconnect-with-cmd.txt)

For `trace-disconnect-without-cmd.txt` just the cable was removed and no command issued, so BlueChi could detect the disconnect. 
In the second case, the command was issued within the time frame the keepalive grants - no event in regards of a timeout or host unreachable was processed. The error `The name :1.10092 was not provided by any .service files` is due to our timeouts in `bluechi-controller` and `bluechictl` - `bluechictl`'s timeout is lower than the one in `bluechi-controller`, so it disconnects from the system bus and the reply from the controller can't find the bus id `bluechictl` previously used (should probably be tweaked in a separate issue/PR). 
I also compiled `libsystemd` with debug symbols and can confirm that both parts ([ERRNO_IS_NEG_DISCONNECT](https://github.com/systemd/systemd/blob/bf35f9c83541785726dce41e54496a07f4841621/src/libsystemd/sd-bus/sd-bus.c#L3283) and [emitting Disconnected signal](https://github.com/systemd/systemd/blob/bf35f9c83541785726dce41e54496a07f4841621/src/libsystemd/sd-bus/sd-bus.c#L3184C9-L3184C9)) are not reached in the second case. I also debugged the poll() main loop a bit and as far as I've seen the ICMP error packages with host unreachable were sent, but not processed by it. 
Looking at [tcp(7)](https://man7.org/linux/man-pages/man7/tcp.7.html) I found:

>  Some applications require a quicker error notification. This can be enabled with the IPPROTO_IP level IP_RECVERR socket option. When this option is enabled, all incoming errors are immediately passed to the user program. Use this option with care — it makes TCP less tolerant to routing changes and other normal network conditions.

Setting this option on the peer bus resulted in this strace:
- [trace-disconnect-with-cmd-fix.txt](https://github.com/eclipse-bluechi/bluechi/files/13701035/trace-disconnect-with-cmd-fix.txt)

Now we get the `EHOSTUNREACH` processed in the poll() loop and a subsequent node disconnected. It still takes a bit of time (longer than our current timeout in BlueChi), but I think that is fine and can be configured per system, e.g. via the retransmit count. 

I also found the `TCP_USER_TIMEOUT` socket option, which triggers an `ETIMEDOUT` and results in `bluechi-controller` to detect the disconnected as well. But this seems rather crude and I think the `IP_RECVERR` is more robust. 
What do you think? @alexlarsson 

Edit: I created a small PR to address this issue: https://github.com/eclipse-bluechi/bluechi/pull/670
@dofmind Could you try out the fix in the PR?

**Comment by dofmind** [comment]
> Edit: I created a small PR to address this issue: #670 @dofmind Could you try out the fix in the PR?

First of all, thanks for your work. I tried out the fix. It gives much less detection time than prior - it takes about 120 seconds, sometimes 60 seconds. As you said, it still takes a bit of time. If it can be configured and can give more small detection time, it will be really great. Thanks.

**Comment by engelmi** [comment]
Hi @dofmind, 
great to read that #670 somewhat helps. At least it enables BlueChi to detect a bit faster. 

The next parameter to tweak for faster detection are the retransmissions - which can only be done on a per-system basis as far as I know (and is quite complex). So I am afraid this part you would need to adjust for your systems independently.

I know that the `net.ipv4.tcp_retries1` (see [tcp(7)](https://man7.org/linux/man-pages/man7/tcp.7.html)) is involved in some way, but it also depends on the RTO (Retransmission Timeout) mechanism where also other options such as `tcp_frto` and `tcp_frto_response` come into play. For example, even though on my system its `net.ipv4.tcp_retries1 = 3`, I can count 7 retransmissions and ~30s till the first ICMP packet is sent - so it takes 30s for BlueChi to detect the disconnect. I can only explain the diff by the RTO mechanism, but haven't investigated this yet.
