### ISSUE TITLE
Allow integration tests to run on multiple hosts

### ISSUE THREAD

**Issue by mwperina** [engelmi/hirte#662]
Currently we have only a single host in CI, so we are emulating multiple hosts with multiple containers. But we need to run integration tests also on multiple hosts to simulate production environment as much as possible.

The goal of the feature is to add test infrastructure to switch between signle and multiple hosts only by changing command line parameters for tmt execution

**Comment by Yarboa** [comment]
@mwperina @engelmi 
I assume we need to dig a bit more with tmt multi host in TF
https://tmt.readthedocs.io/en/latest/guide.html#multihost-testing

Do you still want to run containers? but on different hosts? I assume it will support the pytest configurations

**Comment by engelmi** [comment]
> Do you still want to run containers? but on different hosts? I assume it will support the pytest configurations

@Yarboa I think we'd support two modes for running the tests:
- one host and use containers to simulate multiple agents
- multiple hosts with multiple agents

We probably have to change how we access the controllers/agents host. Currently, we are using podman's API to execute commands inside the container. For multiple hosts I assume we have to use ssh. In order to have one uniform API (and not implement the same stuff twice, once for podman api and again for ssh) I think it would be best to just use ssh for both cases. 
Therefore, I'd first rewrite the current integration tests to use ssh instead of podmans api, which is a quite big change. Then adding multi-host support should be rather easy, I think.

**Comment by Yarboa** [comment]
@engelmi 
I would suggest to got the other way around. with tmt
Better to start with multihost. 2 servers with same network
We could propose this tests as another plan,
later we could start on unified mechanism for tests, 
Please share your thoughts

**Comment by engelmi** [comment]
We'll split this up into multiple PRs:
- [x] renaming `controller` to `machine` in classes and functions (https://github.com/eclipse-bluechi/bluechi/pull/740)
- [x] introducing a `Client` class as a base for a container and ssh one (ssh can be a dummy) (https://github.com/eclipse-bluechi/bluechi/pull/743)
- [x] extracting and encapsulating common `exec_run(...)` into dedicated systemctl and bluechictl classes (easier readability and quicker to see which tool is used) (https://github.com/eclipse-bluechi/bluechi/pull/745)
- [x] implementing ssh client and multihost support (needs investigation how to retrieve IP addresses from hosts in testing farm) (https://github.com/eclipse-bluechi/bluechi/pull/749)
- [x] implementing proper cleanup for ssh/multihost test (reset to initial state, remove added files, etc.) (https://github.com/eclipse-bluechi/bluechi/pull/765)

**Comment by mwperina** [comment]
Closing as done
