### ISSUE TITLE
Create a static library for use by hirte, hirte-node, and hirte-client

### ISSUE THREAD

**Issue by sdunnagan** [engelmi/hirte#79]
## Please describe what you would like to see

Create a static library for use by hirte, hirte-node, and hirte-client.

**Comment by engelmi** [comment]
This is a good tutorial for building static/shared libraries via meson:
https://renenyffenegger.ch/notes/development/languages/C-C-plus-plus/GCC/create-libraries/Meson/index

Essentially, this part here:
https://github.com/containers/hirte/blob/main/libhirte/meson.build#L25-L47
needs to be changed by removing the version (not needed) and using the `static_library()` call instead of `shared_library()`. 

Is this issue about just creating and embedding the static library or also about the structural code changes? E.g. it doesn't make sense to add `libhirte/src/orchestrator.c` to `hirte-node`.

**Comment by sdunnagan** [comment]
Closing this issue since a static library is already in the works with PR #81 .
