### ISSUE TITLE
Unable to build bluechi

### ISSUE THREAD

**Issue by raghulrajn** [engelmi/hirte#986]
Hello Team, 

I tried to build the build the bluechi from source following the instructions given [here](https://github.com/eclipse-bluechi/bluechi/blob/main/README.developer.md#build)

But I get the error as ERROR 'syntax error' at token 'dbus_acquire_svc_system_dbusd' on line 7456. Also tried installing via PPA , that also throws error.

## using PPA
``` console
curl -s --compressed "https://raw.githubusercontent.com/eclipse-bluechi/bluechi-ppa/main/deb/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/bluechi.gpg >/dev/null
curl -s --compressed -o /etc/apt/sources.list.d/bluechi.list "https://raw.githubusercontent.com/eclipse-bluechi/bluechi-ppa/main/deb/bluechi.list"
sudo apt update
sudo apt install bluechi-controller bluechi-agent bluechictl 
```

``` console
ubuntu@ubuntu:~$ sudo apt install bluechi-controller bluechi-agent bluechictl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package bluechi-controller
E: Unable to locate package bluechi-agent
E: Unable to locate package bluechictl
```

## Build from source
``` console
ubuntu@ubuntu:~$ meson compile -C builddir
ninja: Entering directory `/home/raghul/Documents/eclipse/bluechi/builddir'
[27/52] Generating selinux/bluechi.pp.bz2 with a custom command
FAILED: selinux/bluechi.pp.bz2 
/home/raghul/Documents/eclipse/bluechi/selinux/build-selinux.sh selinux/bluechi.pp.bz2 ../selinux/bluechi.te ../selinux/bluechi.fc
make: Entering directory '/home/raghul/Documents/eclipse/bluechi/builddir/selinux-build-32IieQ'
Compiling default bluechi module
bluechi.te:52:ERROR 'syntax error' at token 'dbus_acquire_svc_system_dbusd' on line 7456:
dbus_acquire_svc_system_dbusd(bluechi_t)
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make: *** [/usr/share/selinux/devel/include/Makefile:166: tmp/bluechi.mod] Error 1
make: Leaving directory '/home/raghul/Documents/eclipse/bluechi/builddir/selinux-build-32IieQ'
[36/52] Compiling C object src/client/bluechictl.p/method-status.c.o
ninja: build stopped: subcommand failed.
```

## System Information
- Ubuntu 22.04
- Python 3.10

## Steps to reproduce
```
git clone https://github.com/eclipse-bluechi/bluechi.git
cd bluechi
meson setup builddir
meson compile -C builddir
```

**Comment by engelmi** [comment]
Hi @raghulrajn, 

Regarding the build error:
The build steps in the [README.developer.md](https://github.com/eclipse-bluechi/bluechi/blob/main/README.developer.md#build) are mainly written for centos/fedora systems - which use [SELinux](https://selinuxproject.org/page/Main_Page) by default. Ubuntu doesn't use SELinux and, therefore, when you try to build BlueChi on Ubuntu you have to disable building this package by running:
```bash
meson configure -Dwith_selinux=false builddir
```
So the full steps to build BlueChi on Ubuntu are:
```
git clone https://github.com/eclipse-bluechi/bluechi.git
cd bluechi
meson setup builddir
meson configure -Dwith_selinux=false builddir
meson compile -C builddir
```

Could you try and check if this solves the build issue?

---

Regarding the error with the PPA:
I am not sure why the PPA doesn't work for you. Since `apt` isn't able to find the packages I'd suspect the source list not being updated properly. Can you verify that `/etc/apt/sources.list.d/bluechi.list` exists and contains the URL to the PPA?

**Comment by engelmi** [comment]
Hi @raghulrajn, did this solve the issue?

**Comment by raghulrajn** [comment]
Hi @engelmi , Yes I could build with below command. Sorry for the late response

```
meson configure -Dwith_selinux=false builddir
```

Thank you

**Comment by engelmi** [comment]
Pefect, then lets close this issue :)
