### ISSUE TITLE
Properly handle agent disconnect

### ISSUE THREAD

**Issue by alexlarsson** [engelmi/hirte#99]
When an  agent disconnects we must look at all outstanding requests and jobs for it and terminate them, otherwise a client may wait forever for a repsonse.

**Comment by sdunnagan** [comment]
This was fixed by my PRs #292 and #304.

I was going to next undertake clean-up for unit status subscriptions when agents disconnect,
but came to the conclusion that in that case there is no need to remove anything.  Because
when you're monitoring a node, the agent can go down and back up again, and monitoring
can continue.  So I believe subscriptions only need to be cleaned up when a Hirte client
unsubscribes from unit status notifications from a node.
